//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simpeda
{
    using System;
    using System.Collections.Generic;
    
    public partial class JurusanInstansi
    {
        public JurusanInstansi()
        {
            this.Dosen = new HashSet<Dosen>();
            this.Mahasiswa = new HashSet<Mahasiswa>();
            this.Pegawai = new HashSet<Pegawai>();
        }
    
        public int idJurusan { get; set; }
        public string namaJurusan { get; set; }
        public string alamatJurusan { get; set; }
        public string teleponJurusan { get; set; }
    
        public virtual ICollection<Dosen> Dosen { get; set; }
        public virtual ICollection<Mahasiswa> Mahasiswa { get; set; }
        public virtual ICollection<Pegawai> Pegawai { get; set; }
    }
}
